version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis_1
    restart: unless-stopped
    ports:
      - "6379:6379"
    environment:
      - TZ=Asia/Seoul
      - REDIS_PASSWORD=lldj123414
    command: ["redis-server", "--requirepass", "lldj123414"]
